f1_dbt:
  outputs:
    dev:
      dataset: f1_analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../gcp_credentials/mage-service-account.json
      location: us-central1
      method: service-account
      priority: interactive
      project: f1-telemetry-pipeline-499103
      threads: 1
      type: bigquery
  target: dev
